---
# YAML documents begin with the document separator ---

- hosts: jenkins

  # Task: the list of tasks that will be executed within the play, this section
  # can also be used for pre and post tasks
  tasks:
    - name: Add docker to adhoc_group
      add_host:
        name: docker
        groups: adhoc_group1, adhoc_group2

- hosts: adhoc_group1

  # Task: the list of tasks that will be executed within the play, this section
  # can also be used for pre and post tasks
  tasks:
    - name: Ping all in adhoc_group1
      ping:

# Three dots indicate the end of a YAML document
...
